name: Deploy Backend
on:
  push:
    branches: ["master"]
    paths:
      - backend/**
      - .github/workflows/deploy-backend.yml
  pull_request:
    branches: ["master"]
    paths:
      - backend/**
      - .github/workflows/deploy-backend.yml

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: "./backend/*"
          target: "/var/svc/cost-return-backend"
          rm: true
          strip_components: 1

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            cd "/var/svc/cost-return-backend"
            pip3 install -r requirements.txt
            sudo systemctl daemon-reload
            sudo systemctl restart cost-return.service