name: Periodic-test
on:
  push:
  pull_request:
  schedule:
    - cron: "*/6 * * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tets
        run: echo "test"
